services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - VITE_TURNSTILE_SITE_KEY=${VITE_TURNSTILE_SITE_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
  worker1:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - DATABASE_URL=${DATABASE_URL}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_BUCKET_REGION=${AWS_BUCKET_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
  worker2:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - DATABASE_URL=${DATABASE_URL}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_BUCKET_REGION=${AWS_BUCKET_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
volumes:
  redis_data:
